# Generated by Django 4.2.5 on 2023-10-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_imagen_product_temporada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
