# Generated by Django 4.2.5 on 2023-11-05 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_zona_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='contact_number',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='specifications',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPermits',
        ),
    ]
