# Generated by Django 4.2.5 on 2023-11-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_sale_contact_number_sale_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='contact_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='delivery_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='specifications',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
