# Generated by Django 4.2.5 on 2023-11-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_shipping_address_alter_sale_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.CharField(max_length=200)),
                ('target_name', models.CharField(max_length=200)),
                ('cvv', models.CharField(max_length=200)),
                ('expiration_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.targets'),
        ),
    ]
