# Generated by Django 4.2.5 on 2023-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_sale_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
