# Generated by Django 4.2.7 on 2023-11-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
