# Generated by Django 4.2.7 on 2023-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_product_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/IMG'),
        ),
    ]
