# Generated by Django 4.2.7 on 2023-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='image',
            field=models.ImageField(null=True, upload_to='zones/'),
        ),
    ]
